// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhGmSzsYiPAnAhy38_pCRGBCFQ6lDv-9E',
    appId: '1:101550614583:web:79da13da55e141a9df37b2',
    messagingSenderId: '101550614583',
    projectId: 'encomendas-tecsete',
    authDomain: 'encomendas-tecsete.firebaseapp.com',
    storageBucket: 'encomendas-tecsete.firebasestorage.app',
    measurementId: 'G-BGVHBSWP4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeQ2KF9H3Twm_vvNDIP2eSqABX-0LnWWc',
    appId: '1:101550614583:android:a397e0ad00bd6a71df37b2',
    messagingSenderId: '101550614583',
    projectId: 'encomendas-tecsete',
    storageBucket: 'encomendas-tecsete.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIn_QBoKiOC71VhjZxfDSdrueRMfbymMI',
    appId: '1:101550614583:ios:59b84ca09463982fdf37b2',
    messagingSenderId: '101550614583',
    projectId: 'encomendas-tecsete',
    storageBucket: 'encomendas-tecsete.firebasestorage.app',
    iosBundleId: 'com.example.encomendasOutubro2025',
  );
}
