platform :ios, '15.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

target 'Runner' do
    use_frameworks! :linkage => :static
    use_modular_headers!

    flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

flutter_additional_ios_build_settings(target)